### ISSUE TITLE
Fial to import moviepy

### ISSUE THREAD

**Issue by Prequels** [nicolomantini/Influencer-bot#6]
Fail to import moviepy. Need only for Video upload.
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from post import prep_post, upload
  File "/home/cam/Desktop/Influencer-bot-master/post.py", line 3, in <module>
    from resizeimage import resizeimage
ModuleNotFoundError: No module named 'resizeimage'

What's going on here im pretty sure ive added everything correctly..

**Comment by Prequels** [comment]
Fixed // Just need to comment out the resize image 

#  from resizeimage import resizeimage
